package com.pywl.ebangbang_rider.app_final;

/**
 * Created by Harry on 2018/11/6.
 * 处理RxJava切断管道方法
 * 命名方法 - 类名+方法名
 */
public enum DisposableFinal {

    LOGIN_ACTIVITY_LOGIN,
    HOME_WAITING_FOR_GOODS_FRAGMENT_GET_DATA_LIST,
    HOME_WAITING_FOR_GOODS_FRAGMENT_ARRIVAL,
    HOME_BE_SENDING_OUT_GET_DATA_LIST,
    HOME_BE_SENDING_OUT_COMPLETE,
    ORDER_TAKING_MANAGE_SAVE,
    ORDER_TAKING_MANAGE_GET_STATUS,
    FEEDBACK_COMMIT,
    COMPLETED_ACTIVITY_GET_DATA_LIST,
    CANCEL_ORDER_ACTIVITY_GET_DATA_LIST,
    MAIN_ACTIVITY_POST_ADDRESS,
}
